services:
    svelte-app:
        build:
            context: ./svelte-app
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - ./svelte-app:/app
            - svelte_node_modules:/app/node_modules
        env_file:
            - ./svelte-app/.env
        environment:
            NODE_ENV: development
            CHOKIDAR_USEPOLLING: "true"
        depends_on:
            - directus

    directus:
        image: directus/directus:latest
        ports:
            - 8055:8055
        depends_on:
            - postgres
        volumes:
            - ./directus/uploads:/directus/uploads
            - ./directus/extensions:/directus/extensions
        environment:
            SECRET: ${DIRECTUS_SECRET}
            DB_CLIENT: ${DB_CLIENT}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
            WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}
            CORS_ENABLED: ${CORS_ENABLED}
            CORS_ORIGIN: ${CORS_ORIGIN}

    postgres:
        image: postgres:16-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    svelte_node_modules:
    postgres_data:
